#!/usr/bin/env bash

set -e

export PYTHONPATH="bin"

for f in test/*.py
do
    echo "--- $f"
    python3 "$f"
done

echo "Bash test"
dir=$( dirname "${BASH_SOURCE[0]}" )

bats ${dir}/test_helper
${dir}/../windows/test/run
